# Generated by Django 4.2 on 2023-04-28 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_category_name_category_subscribers'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='postCategory',
            new_name='category',
        ),
    ]
