# Generated by Django 4.2.2 on 2023-06-24 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_alter_category_name_alter_post_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='name_en_us',
            field=models.CharField(help_text='Enter the name of the category (maximum 64 characters).', max_length=64, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='category',
            name='name_ru',
            field=models.CharField(help_text='Enter the name of the category (maximum 64 characters).', max_length=64, null=True, unique=True, verbose_name='Category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_en_us',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.AddField(
            model_name='post',
            name='title_ru',
            field=models.CharField(max_length=255, null=True, verbose_name='title'),
        ),
        migrations.CreateModel(
            name='PostCategory_ru',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'Категория новости [ru]',
                'verbose_name_plural': 'Категории новостей [ru]',
                'db_table': 'news_postcategory_ru',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
        migrations.CreateModel(
            name='PostCategory_en_us',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.category')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='news.post')),
            ],
            options={
                'verbose_name': 'Категория новости [en-us]',
                'verbose_name_plural': 'Категории новостей [en-us]',
                'db_table': 'news_postcategory_en_us',
                'db_tablespace': '',
                'auto_created': False,
            },
        ),
    ]
