# Generated by Django 4.2.2 on 2023-06-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_category_name_en_us_category_name_ru_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Select the categories for this post.', through='news.PostCategory', to='news.category', verbose_name='PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category', verbose_name='PostCategory'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category', verbose_name='PostCategory'),
        ),
    ]
