# Generated by Django 4.2.2 on 2023-06-25 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_alter_post_category_alter_post_category_en_us_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(help_text='Select the categories for this post.', through='news.PostCategory', to='news.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_en_us',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category_ru',
            field=models.ManyToManyField(help_text='Select the categories for this post.', null=True, through='news.PostCategory', to='news.category'),
        ),
    ]
